classes:
- system.backupninja.server.single
- system.xtrabackup.server.single
- system.ceph.backup.server.single
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.backup
parameters:
  _param:
<<<<<<< HEAD
    backupninja_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9swSqREOO60wglmmBiHkF/Y+baBoRWkjnmxQQrDuOJTDfn4SMHsFxg2BohFVECtkG7EWfhdXA3eBXpHrF9V5qY0ep3oZL9hIB2Q/3NNs5Rup9C+CU8s8/HR87WHHnFvGSHDlEzlCUxGkrpVh48mm8Hs6jzJ/saDsSMn9bMeGXmkFqMitViB//3fE+cjoKKps4zkfE1uudC9+B52wnED9eUeH81MFVh56uNPsWgeSzYG/0uA41iBSTJGqWAoHiM3mwuPp+MGSTeMVL6gQ+p0FVPXvLunm/3+3AqhGuqHPV7LEVj2kGCIinowrtUH/wkj58pLO7abUd0/pTukv17dZV
    xtrabackup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9swSqREOO60wglmmBiHkF/Y+baBoRWkjnmxQQrDuOJTDfn4SMHsFxg2BohFVECtkG7EWfhdXA3eBXpHrF9V5qY0ep3oZL9hIB2Q/3NNs5Rup9C+CU8s8/HR87WHHnFvGSHDlEzlCUxGkrpVh48mm8Hs6jzJ/saDsSMn9bMeGXmkFqMitViB//3fE+cjoKKps4zkfE1uudC9+B52wnED9eUeH81MFVh56uNPsWgeSzYG/0uA41iBSTJGqWAoHiM3mwuPp+MGSTeMVL6gQ+p0FVPXvLunm/3+3AqhGuqHPV7LEVj2kGCIinowrtUH/wkj58pLO7abUd0/pTukv17dZV
    ceph_backup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9swSqREOO60wglmmBiHkF/Y+baBoRWkjnmxQQrDuOJTDfn4SMHsFxg2BohFVECtkG7EWfhdXA3eBXpHrF9V5qY0ep3oZL9hIB2Q/3NNs5Rup9C+CU8s8/HR87WHHnFvGSHDlEzlCUxGkrpVh48mm8Hs6jzJ/saDsSMn9bMeGXmkFqMitViB//3fE+cjoKKps4zkfE1uudC9+B52wnED9eUeH81MFVh56uNPsWgeSzYG/0uA41iBSTJGqWAoHiM3mwuPp+MGSTeMVL6gQ+p0FVPXvLunm/3+3AqhGuqHPV7LEVj2kGCIinowrtUH/wkj58pLO7abUd0/pTukv17dZV
=======
    backupninja_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpfJlXe7iSvKUUkWPVEMOSgxcS6PZumV2iny8nL4Q0ND/HSfiOoeKCX1OgMulMDckbEij1JBfLfgyU1TD2ixBtnAduTvrjYwjQ6XFZWoGmXEfbF9fGzeyt9EIS0lQlrc2m/nQrKkw4jkc6f1RugBZXa4JEYgXrr6EoEvlYJ14mmh7YbKJY+e62lQMXBi84yZJs/XSUMn7Ycg5n5KLANH5oWHWhSQlSZNsnDbQ3XPe1jEUOp9XhcnCqMl9OZtY6wGiOcKdyU1KK4D2ZXy5JLeotrn+ocOqC5N0lE2qBA8nhjt4lH1FfSxeP6CiqQkUorKOUDUKZnMXk9Do/apd4UHUz
    xtrabackup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpfJlXe7iSvKUUkWPVEMOSgxcS6PZumV2iny8nL4Q0ND/HSfiOoeKCX1OgMulMDckbEij1JBfLfgyU1TD2ixBtnAduTvrjYwjQ6XFZWoGmXEfbF9fGzeyt9EIS0lQlrc2m/nQrKkw4jkc6f1RugBZXa4JEYgXrr6EoEvlYJ14mmh7YbKJY+e62lQMXBi84yZJs/XSUMn7Ycg5n5KLANH5oWHWhSQlSZNsnDbQ3XPe1jEUOp9XhcnCqMl9OZtY6wGiOcKdyU1KK4D2ZXy5JLeotrn+ocOqC5N0lE2qBA8nhjt4lH1FfSxeP6CiqQkUorKOUDUKZnMXk9Do/apd4UHUz
    ceph_backup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpfJlXe7iSvKUUkWPVEMOSgxcS6PZumV2iny8nL4Q0ND/HSfiOoeKCX1OgMulMDckbEij1JBfLfgyU1TD2ixBtnAduTvrjYwjQ6XFZWoGmXEfbF9fGzeyt9EIS0lQlrc2m/nQrKkw4jkc6f1RugBZXa4JEYgXrr6EoEvlYJ14mmh7YbKJY+e62lQMXBi84yZJs/XSUMn7Ycg5n5KLANH5oWHWhSQlSZNsnDbQ3XPe1jEUOp9XhcnCqMl9OZtY6wGiOcKdyU1KK4D2ZXy5JLeotrn+ocOqC5N0lE2qBA8nhjt4lH1FfSxeP6CiqQkUorKOUDUKZnMXk9Do/apd4UHUz
>>>>>>> 1169223ea46f1a2fe34fd403f13d3e5ed766cdc7
  backupninja:
    server:
      home_dir: /srv/volumes/backup/backupninja
  xtrabackup:
    server:
      backup_dir: /srv/volumes/backup/xtrabackup
  ceph:
    backup:
      backup_dir: /srv/volumes/backup/ceph
<<<<<<< HEAD
  

=======
>>>>>>> 1169223ea46f1a2fe34fd403f13d3e5ed766cdc7
